### PR TITLE
Hint for whitespace before Mario pyramid

### PR DESCRIPTION
**Pull request by amandavosburgh**

### CODE REVIEW

**Comment by amandavosburgh** [comment]
@tlively

**Comment by amandavosburgh** [comment]
@brianyu28 Sorry for the confusion; this doesn't work. However, I thought [this](https://github.com/amandavosburgh/checks/blob/mario-extra-space/cs50/2017/fall/mario/less/check50/__init__.py) would work, but it doesn't print the hint as intended either... Thoughts?

**Comment by brianyu28** [comment]
@amandavosburgh 

Hey Amanda!

This looks great, thanks so much. Could you email me (brian@cs50.harvard.edu) a sample `mario.c` file for which the hint is supposed to apply? I'll take a look and see if I can figure out what's going on.

**Comment by brianyu28** [comment]
Thanks, @amandavosburgh!

**Pull request merged**
